name: kitsu_api
description: Kitsu api client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.6.0
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.8
  equatable: ^2.0.5
dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.2